#!/usr/bin/env python3

"""Phase 2 packet decoder CLI.

The implementation lives in the packet_decoder package. This file keeps the
original command-line entrypoint stable.
"""

import argparse
import logging

from packet_decoder import decode_pcap
from packet_decoder.utils import configure_logging


LOGGER = logging.getLogger(__name__)
OUTPUT_MODES = ("quiet", "normal", "verbose", "debug")

# Selection mode for terminal output:
# python3 packet_decode.py capture.pcap --mode quiet: ẩn output thông thường, chỉ giữ lỗi/cảnh báo quan trọng.
# python3 packet_decode.py capture.pcap --mode normal: banner và thống kê.
# python3 packet_decode.py capture.pcap --mode verbose: summary từng packet.
# python3 packet_decode.py capture.pcap --mode debug: field chi tiết và payload.

def get_arguments():
    parser = argparse.ArgumentParser(
        description="Phase 2 PCAP packet decoder"
    )
    parser.add_argument(
        "pcap",
        help="PCAP file generated by packet_capture.py",
    )
    parser.add_argument(
        "-n",
        "--limit",
        type=int,
        default=None,
        help="Maximum number of packets to decode",
    )
    parser.add_argument(
        "--mode",
        choices=OUTPUT_MODES,
        default="normal",
        help=(
            "Terminal output: quiet hides normal output, normal shows "
            "banner and statistics, verbose shows packet summaries, "
            "debug shows all decoded fields and payload previews"
        ),
    )
    return parser.parse_args()


def main():
    args = get_arguments()
    configure_logging(args.mode)

    if args.mode != "quiet":
        LOGGER.info("CUSTOM IDS - PHASE 2 PACKET DECODER")
        LOGGER.info("PCAP file: %s", args.pcap)
        LOGGER.info("Output mode: %s", args.mode)
        LOGGER.info("Limit: %s", args.limit if args.limit is not None else "all packets")

    decode_pcap(
        filename=args.pcap,
        packet_limit=args.limit,
        output_mode=args.mode,
    )


if __name__ == "__main__":
    main()
