#!/usr/bin/env python3

"""Phase 2 packet decoder CLI and result-file runner."""

import argparse
import logging
from pathlib import Path

from packet_decoder import decode_pcap


LOGGER = logging.getLogger(__name__)
OUTPUT_MODES = ("quiet", "normal", "verbose", "debug")


def get_arguments(arguments=None):
	parser = argparse.ArgumentParser(
		description="Phase 2 PCAP packet decoder"
	)
	parser.add_argument(
		"pcap",
		help="PCAP file generated by packet_capture.py",
	)
	parser.add_argument(
		"-n",
		"--limit",
		type=int,
		default=None,
		help="Maximum number of packets to decode",
	)
	parser.add_argument(
		"--mode",
		choices=OUTPUT_MODES,
		default="normal",
		help=(
			"Terminal/file output: quiet shows errors, normal shows "
			"statistics, verbose shows packet summaries, debug shows "
			"all decoded fields and payload previews"
		),
	)
	parser.add_argument(
		"--result",
		default="packet_decoder_result.txt",
		help="Text file for decoder output (default: packet_decoder_result.txt)",
	)
	return parser.parse_args(arguments)


def _configure_result_logging(result_file, output_mode):
	levels = {
		"quiet": logging.ERROR,
		"normal": logging.INFO,
		"verbose": logging.INFO,
		"debug": logging.DEBUG,
	}
	result_path = Path(result_file)
	result_path.parent.mkdir(parents=True, exist_ok=True)
	handler = logging.FileHandler(result_path, mode="w", encoding="utf-8")
	handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))

	root_logger = logging.getLogger()
	previous_level = root_logger.level
	root_logger.setLevel(levels[output_mode])
	root_logger.addHandler(handler)
	return root_logger, previous_level, handler


def decode_pcap_to_file(filename, result_file, packet_limit=None, output_mode="normal"):
	"""Decode a PCAP and write the complete selected output to a text file."""
	root_logger, previous_level, handler = _configure_result_logging(
		result_file,
		output_mode,
	)
	try:
		LOGGER.info("CUSTOM IDS - PHASE 2 PACKET DECODER")
		LOGGER.info("PCAP file: %s", filename)
		LOGGER.info("Output mode: %s", output_mode)
		LOGGER.info(
			"Limit: %s",
			packet_limit if packet_limit is not None else "all packets",
		)
		return decode_pcap(
			filename=filename,
			packet_limit=packet_limit,
			output_mode=output_mode,
		)
	finally:
		handler.flush()
		root_logger.removeHandler(handler)
		handler.close()
		root_logger.setLevel(previous_level)


def main(arguments=None):
	args = get_arguments(arguments)
	decode_pcap_to_file(
		filename=args.pcap,
		result_file=args.result,
		packet_limit=args.limit,
		output_mode=args.mode,
	)


if __name__ == "__main__":
	main()

